name: djs-v13

on:
  push:
    branches: main
  pull_request:
    branches: "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [">=v16.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install dependencies
        run: npm i

      - name: Run Test
        run: node index.js
